# creating an ubuntu based image
FROM ubuntu

RUN apt update

RUN apt install -y lsb-core

#install the jdk-18 java version
RUN apt install -y openjdk-18-jdk openjdk-18-demo openjdk-18-doc openjdk-18-jre-headless openjdk-18-source 

